/** 视图切换类型 */
export enum ViewStateType {
    /** 初始状态 */
    None = 0,
    /** 显示 */
    Visible = 1,
    /** 位置 */
    Position = 2,
    /** 旋转 */
    Rotation = 3,
    /** 缩放 */
    Scale = 4,
    /** 尺寸 */
    Size = 5,
    /** 锚点 */
    AnchorPoint = 6,
    /** 文本 */
    Text = 7,
    /** 资源 */
    Asset = 8,
    /** 颜色 */
    Color = 9,
    /** 透明度 */
    Alpha = 10,
    /** 选中状态 */
    Toggle = 11,
    /** 文字大小 */
    FontSize = 12,
    /** 动画名称 */
    AnimName = 13,
    /** 进度 */
    Progress = 14,
    /** 组 */
    Group = 15,
    /** 材质 */
    Material = 16,
    /** 自定义 */
    Custom = 17,
}