// Code generated by protogen.
// DO NOT EDIT!!!
// source:  act_types.proto

/*
Package Example is a generated protocol buffer package.

It is generated from these files:
act_types.proto

It has these top-level messages:
    act_types
    act_typesArray
*/

import { IMessage } from "./message";

//namespace Example {


    
    export class act_types implements IMessage {

    
        /*
        *系统ID
        */
        id      :number;
        /*
        *活动ID
        */
        t       :string;
        /*
        *描述
        */
        m       :string;
        /*
        *跨服区间类型
        */
        needSev :string;
        /*
        *自动生成跨服区间
        */
        sev     :string;
        /*
        *数据保存
        */
        save    :string;
        /*
        *活动参与日志
        */
        actLog  :string;
        /*
        *存储键值
        */
        hKey    :string;
        /*
        *新类型给前端使用
        */
        ntype   :string;
        /*
        *插图
        */
        banner  :string;

        constructor() {
            this.id      = 0;
        }

        className(): string {
            return "act_types";
        }
    }
    
    export class act_typesArray implements IMessage {

    
        Keys      :Array<number>;
        Items     :Array<act_types>;
        TableHash :string;
        DataHash  :string;

        constructor() {
        }

        className(): string {
            return "act_typesArray";
        }
    }

//}
