// Code generated by protogen.
// DO NOT EDIT!!!
// source:  buffModify.proto

/*
Package Example is a generated protocol buffer package.

It is generated from these files:
buffModify.proto

It has these top-level messages:
    buffModify
    buffModifyArray
*/

import { IMessage } from "./message";

//namespace Example {


    
    export class buffModify implements IMessage {

    
        /*
        *编号
        */
        id        :number;
        /*
        *条件
        */
        condition :string;
        /*
        *修改类型
        */
        type      :string;
        /*
        *是否替换
        */
        replace   :string;
        /*
        *系数
        */
        param1    :string;
        /*
        *系数最大值
        */
        param2    :string;
        /*
        *常数
        */
        param3    :string;
        /*
        *额外参数
        */
        param4    :string;

        constructor() {
            this.id        = 0;
        }

        className(): string {
            return "buffModify";
        }
    }
    
    export class buffModifyArray implements IMessage {

    
        Keys      :Array<number>;
        Items     :Array<buffModify>;
        TableHash :string;
        DataHash  :string;

        constructor() {
        }

        className(): string {
            return "buffModifyArray";
        }
    }

//}
