// Code generated by protogen.
// DO NOT EDIT!!!
// source:  buff.proto

/*
Package Example is a generated protocol buffer package.

It is generated from these files:
buff.proto

It has these top-level messages:
    buff
    buffArray
*/

import { IMessage } from "./message";

//namespace Example {


    
    export class buff implements IMessage {

    
        /*
        *编号
        */
        id                 :number;
        /*
        *buff名称
        */
        name               :string;
        /*
        *buff描述
        */
        desc               :string;
        /*
        *buff类型
        */
        buffType           :string;
        /*
        *是否debuff
        */
        isDebuff           :string;
        /*
        *是否控制
        */
        isControl          :string;
        /*
        *buff标识
        */
        tag                :string;
        /*
        *修改器
        */
        modify             :string;
        /*
        *buff流程
        */
        process            :string;
        /*
        *衍生buff
        */
        derive             :string;
        /*
        *衍生buff跟随移除
        */
        deriveFollowRemove :string;
        /*
        *概率
        */
        rate               :string;
        /*
        *生效间隔
        */
        execInterval       :string;
        /*
        *触发时机
        */
        trigger            :string;
        /*
        *触发条件
        */
        triggerCondition   :string;
        /*
        *执行条件
        */
        execCondition      :string;
        /*
        *触发几次后移除
        */
        removeTriggerCount :string;
        /*
        *移除层数
        */
        removeCount        :string;
        /*
        *不能被其他buff移除
        */
        notRemove          :string;
        /*
        *施加者死亡移除
        */
        withActor          :string;
        /*
        *目标
        */
        target             :string;
        /*
        *效果类型
        */
        ability            :string;
        /*
        *系数
        */
        param1             :string;
        /*
        *系数最大值
        */
        param2             :string;
        /*
        *常数
        */
        param3             :string;
        /*
        *额外参数
        */
        param4             :string;
        /*
        *持续时间
        */
        time               :string;
        /*
        *buff叠加类型
        */
        overlap            :string;
        /*
        *同id积累最大数量
        */
        overlapLimit       :string;
        /*
        *表现id
        */
        playerId           :string;

        constructor() {
            this.id                 = 0;
        }

        className(): string {
            return "buff";
        }
    }
    
    export class buffArray implements IMessage {

    
        Keys      :Array<number>;
        Items     :Array<buff>;
        TableHash :string;
        DataHash  :string;

        constructor() {
        }

        className(): string {
            return "buffArray";
        }
    }

//}
