// Code generated by protogen.
// DO NOT EDIT!!!
// source:  skill.proto

/*
Package Example is a generated protocol buffer package.

It is generated from these files:
skill.proto

It has these top-level messages:
    skill
    skillArray
*/

import { IMessage } from "./message";

//namespace Example {


    
    export class skill implements IMessage {

    
        /*
        *编号
        */
        id               :number;
        /*
        *技能id
        */
        skillGroup       :string;
        /*
        *技能类型
        */
        type             :string;
        /*
        *技能优先级
        */
        sort             :string;
        /*
        *是否有动作
        */
        hasAction        :string;
        /*
        *是否自动释放
        */
        autoUse          :string;
        /*
        *技能名称
        */
        name             :string;
        /*
        *技能描述
        */
        desc             :string;
        /*
        *技能图标
        */
        icon             :string;
        /*
        *回复能量值
        */
        energy           :string;
        /*
        *技能流程
        */
        processKey       :string;
        /*
        *可由自身触发
        */
        canTriggerBySelf :string;
        /*
        *不可被打断
        */
        notInterrupt     :string;
        /*
        *前摇时间
        */
        before           :string;
        /*
        *施法时间
        */
        cast             :string;
        /*
        *作用后摇
        */
        castAfter        :string;
        /*
        *后摇时间
        */
        after            :string;
        /*
        *暂停时间
        */
        pauseTime        :string;
        /*
        *命中延时
        */
        hitDelay         :string;
        /*
        *施法目标类型
        */
        targetType       :string;
        /*
        *均摊伤害
        */
        shareOut         :string;
        /*
        *施法距离
        */
        castRange        :string;
        /*
        *单位命中次数上限
        */
        hitLimit         :string;
        /*
        *伤害系数
        */
        percent          :string;
        /*
        *技能初始找人
        */
        find1            :string;
        /*
        *技能作用找人
        */
        find2            :string;
        /*
        *子弹作用找人
        */
        find3            :string;
        /*
        *初始冷却
        */
        firstCd          :string;
        /*
        *冷却时间
        */
        cd               :string;
        /*
        *冷却模式控制
        */
        cdControl        :string;
        /*
        *子弹配置
        */
        bullet           :string;
        /*
        *子弹位置设置
        */
        bulletPosType    :string;
        /*
        *衍生技能
        */
        derive           :string;
        /*
        *buff
        */
        buff             :string;
        /*
        *buff描述
        */
        buffDesc         :string;
        /*
        *表现id
        */
        playerId         :string;

        constructor() {
            this.id               = 0;
        }

        className(): string {
            return "skill";
        }
    }
    
    export class skillArray implements IMessage {

    
        Keys      :Array<number>;
        Items     :Array<skill>;
        TableHash :string;
        DataHash  :string;

        constructor() {
        }

        className(): string {
            return "skillArray";
        }
    }

//}
